name: remote ssh command
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: install ssh key
      uses: shimataro/ssh-key-action@v2
      with: 
        key: ${{ secrets.PRIVADA }}
        known_hosts: ${{ secrets.KNOW_HOST }}
    
    - name: checkout
      uses: actions/checkout@v2
  
    - name: Deploy with  rsync
      run: rsync -avz . ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:.
    
    - name: Build
      run: ssh ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} npm run build
